baseURL: 'https://cristian.livadaru.net'
languageCode: en-us
title: My personal view on things
theme: hugo-theme-cleanwhite
copyright: Cristian Livadaru
pluralizeListTitles: false
pygmentsUseClasses: true
pygmentsCodeFences: true
disablePathToLower: true
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
taxonomies:
  category: categories
  tag: tags
permalinks:
  post: /:slug/
outputs:
  home:
    - HTML
    - RSS
      #    - Algolia
params:
  header_image: 'header/dominik-vanyi-410261-2.jpg'
  social:
    rss: true
      # email: youremail@gmail.com
    linkedin: 'https://www.linkedin.com/in/livadaru'
      # stackoverflow: 'https://stackoverflow.com/users/1373026'
    twitter: https://twitter.com/crisl_at
    github: 'https://github.com/lcx'
# see all settings here https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/master/exampleSite/config.toml
